# Generated by Django 5.2.16 on 2026-09-07 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0018_alter_registropadron_identificador_qr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=120)),
                ('entidad', models.CharField(max_length=120)),
                ('entidad_id', models.CharField(blank=True, max_length=80)),
                ('datos_anteriores', models.JSONField(blank=True, default=dict)),
                ('datos_nuevos', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('agente_usuario', models.CharField(blank=True, max_length=300)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to='elecciones.eleccion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en', '-id'),
                'indexes': [models.Index(fields=['accion', 'creado_en'], name='auditoria_accion_fecha_idx'), models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_idx')],
            },
        ),
    ]
