# Generated by Django 6.0.7 on 2026-07-24 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_code', models.CharField(max_length=120)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='elecciones.eleccion')),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['eleccion', 'voter_code'], name='asistencia__eleccio_357671_idx')],
                'constraints': [models.UniqueConstraint(fields=('eleccion', 'voter_code'), name='unique_attendance_per_election')],
            },
        ),
    ]
