# Generated by Django 6.0.7 on 2026-07-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='voter_code',
            field=models.CharField(max_length=180),
        ),
    ]
