# Generated by Django 5.2.8 on 2026-08-10 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_registro_participacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
