# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_delete_asistencia'),
        ('mesas', '0001_initial'),
        ('padron', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.AlterField(
            model_name='registroparticipacion',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='mesas.mesa'),
        ),
        migrations.AlterField(
            model_name='registroparticipacion',
            name='registro_padron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='padron.registropadron'),
        ),
        ],
    )]
