# Generated by Django 5.2.16 on 2026-09-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='Claustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'elecciones_claustro',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'elecciones_departamento',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'elecciones_sede',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'elecciones_turno',
                'ordering': ('hora_inicio', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='FechaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('roles_destinatarios', models.JSONField(default=list)),
                ('asunto_notificacion', models.CharField(max_length=180)),
                ('mensaje_notificacion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('claustros', models.ManyToManyField(db_table='elecciones_fechaadministrativa_claustros', related_name='fechas_administrativas', to='parametros.claustro')),
            ],
            options={
                'db_table': 'elecciones_fechaadministrativa',
                'ordering': ('nombre',),
            },
        ),
        ],
    )]
