# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0019_remove_asignacionmesa_mesa_and_more'),
        ('padron', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='numero')),
                ('generada_automaticamente', models.BooleanField(default=False)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.eleccion')),
                ('eleccion_claustro_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.eleccionclaustrodepartamento')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='parametros.sede')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='parametros.turno')),
            ],
            options={
                'db_table': 'elecciones_mesa',
                'ordering': ['eleccion_id', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_mesa', to='padron.registropadron')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_padron', to='mesas.mesa')),
            ],
            options={
                'db_table': 'elecciones_asignacionmesa',
            },
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('eleccion', 'numero'), name='unique_mesa_per_eleccion'),
        ),
        ],
    )]
