# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0019_remove_asignacionmesa_mesa_and_more'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='legajo')),
                ('nombre', models.CharField(max_length=180, verbose_name='nombre')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='DNI')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
            ],
            options={
                'db_table': 'elecciones_elector',
                'ordering': ['legajo'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='padrones/%Y/%m/%d')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('huella_archivo', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('previsualizada', 'Previsualizada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='previsualizada', max_length=16)),
                ('cantidad_filas', models.PositiveIntegerField(default=0)),
                ('cantidad_validas', models.PositiveIntegerField(default=0)),
                ('cantidad_errores', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to='elecciones.eleccion')),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to='elecciones.eleccionclaustro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elecciones_importacionpadron',
                'ordering': ('-creada_en',),
            },
        ),
        migrations.CreateModel(
            name='ErrorImportacionPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(blank=True, null=True)),
                ('campo', models.CharField(blank=True, max_length=64)),
                ('mensaje', models.CharField(max_length=300)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='padron.importacionpadron')),
            ],
            options={
                'db_table': 'elecciones_errorimportacionpadron',
                'ordering': ('fila', 'id'),
            },
        ),
        migrations.CreateModel(
            name='RegistroPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('identificador_qr', models.CharField(blank=True, editable=False, max_length=8, unique=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.eleccion')),
                ('eleccion_claustro_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.eleccionclaustrodepartamento')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='padron.elector')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='parametros.sede')),
            ],
            options={
                'db_table': 'elecciones_registropadron',
                'constraints': [models.UniqueConstraint(fields=('elector', 'eleccion'), name='elector_unico_por_eleccion')],
            },
        ),
        ],
    )]
