# Generated by Django - add extra fields for padron
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='tiene_discapacidad',
            field=models.BooleanField(default=False, verbose_name='tiene discapacidad'),
        ),
        migrations.AddField(
            model_name='elector',
            name='departamento_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electores_principal', to='parametros.departamento'),
        ),
        migrations.AddField(
            model_name='registropadron',
            name='nivel',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
