# Generated by Django 5.2.8 on 2026-10-02 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0020_delete_elector_delete_envionotificacion_and_more'),
        ('padron', '0004_merge_0002_emision_qr_0003_separar_apellido'),
        ('parametros', '0003_retirar_mensaje_embebido'),
        ('partidos', '0012_filtros_independientes_de_alcance'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoInclusionPadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE elecciones_elector ADD COLUMN IF NOT EXISTS tipo_documento varchar(30) NOT NULL DEFAULT 'DNI'",
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='elector',
                    name='tipo_documento',
                    field=models.CharField(default='DNI', max_length=30, verbose_name='tipo documento'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='registropadron',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='parametros.sede', verbose_name='sede donde cursa'),
        ),
        migrations.CreateModel(
            name='CondicionInclusionPadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('departamento', 'Departamento'), ('departamento_principal', 'Departamento principal'), ('nivel', 'Nivel'), ('sede_donde_cursa', 'Sede donde cursa'), ('discapacidad', 'Tiene discapacidad')], max_length=32)),
                ('operador', models.CharField(choices=[('igual', 'Es igual a'), ('en', 'Está incluido en'), ('mayor', 'Es mayor que'), ('mayor_igual', 'Es mayor o igual que'), ('menor', 'Es menor que'), ('menor_igual', 'Es menor o igual que')], max_length=16)),
                ('valor', models.CharField(help_text="Para 'Está incluido en', separe los valores con comas.", max_length=500)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='padron.grupoinclusionpadronvotacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('calculado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='padrones_votacion', to='elecciones.eleccionclaustro')),
            ],
            options={
                'ordering': ('nombre', 'id'),
            },
        ),
        migrations.AddField(
            model_name='grupoinclusionpadronvotacion',
            name='padron_votacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_inclusion', to='padron.padronvotacion'),
        ),
        migrations.CreateModel(
            name='ConfiguracionSedePadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion_claustro_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_padron_votacion', to='elecciones.eleccionclaustrodepartamento')),
                ('sede_predeterminada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_predeterminadas_padron', to='elecciones.eleccionclaustrodepartamentosede')),
                ('padron_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_sede', to='padron.padronvotacion')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionPadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculada_en', models.DateTimeField(auto_now_add=True)),
                ('registro_padron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_padrones_votacion', to='padron.registropadron')),
                ('sede_asignada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_padrones_votacion', to='elecciones.eleccionclaustrodepartamentosede')),
                ('padron_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='padron.padronvotacion')),
            ],
            options={
                'ordering': ('padron_votacion', 'registro_padron'),
            },
        ),
        migrations.CreateModel(
            name='PuestoPadronVotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('padron_votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos_configurados', to='padron.padronvotacion')),
                ('puesto_eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_padron_votacion', to='partidos.puestoeleccion')),
            ],
        ),
        migrations.AddField(
            model_name='padronvotacion',
            name='puestos',
            field=models.ManyToManyField(related_name='padrones_votacion', through='padron.PuestoPadronVotacion', to='partidos.puestoeleccion'),
        ),
        migrations.CreateModel(
            name='ReglaAsignacionSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('departamento', 'Departamento'), ('departamento_principal', 'Departamento principal'), ('nivel', 'Nivel'), ('sede_donde_cursa', 'Sede donde cursa'), ('discapacidad', 'Tiene discapacidad')], max_length=32)),
                ('operador', models.CharField(choices=[('igual', 'Es igual a'), ('en', 'Está incluido en'), ('mayor', 'Es mayor que'), ('mayor_igual', 'Es mayor o igual que'), ('menor', 'Es menor que'), ('menor_igual', 'Es menor o igual que')], max_length=16)),
                ('valor', models.CharField(help_text="Para 'Está incluido en', separe los valores con comas.", max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='padron.configuracionsedepadronvotacion')),
                ('sede_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_asignacion_padron', to='elecciones.eleccionclaustrodepartamentosede')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='configuracionsedepadronvotacion',
            constraint=models.UniqueConstraint(fields=('padron_votacion', 'eleccion_claustro_departamento'), name='config_sede_unica_por_padron_depto'),
        ),
        migrations.AddConstraint(
            model_name='asignacionpadronvotacion',
            constraint=models.UniqueConstraint(fields=('padron_votacion', 'registro_padron'), name='registro_unico_por_padron_votacion'),
        ),
        migrations.AddConstraint(
            model_name='puestopadronvotacion',
            constraint=models.UniqueConstraint(fields=('padron_votacion', 'puesto_eleccion'), name='puesto_unico_por_padron_votacion'),
        ),
        migrations.AddConstraint(
            model_name='padronvotacion',
            constraint=models.UniqueConstraint(fields=('eleccion_claustro', 'nombre'), name='padron_votacion_nombre_unico'),
        ),
    ]
