# Generated by Django 5.2.8 on 2026-09-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0004_merge_0002_emision_qr_0003_separar_apellido'),
    ]

    # Una copia local de desarrollo pudo haber creado antes la columna al
    # aplicar 0005_padrones_votacion. Hacer la migración tolerante a esa
    # columna preexistente mantiene los datos y permite actualizarla después.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE elecciones_elector ADD COLUMN IF NOT EXISTS tipo_documento varchar(30) NOT NULL DEFAULT 'DNI'",
                    migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='elector',
                    name='tipo_documento',
                    field=models.CharField(default='DNI', max_length=30, verbose_name='tipo documento'),
                ),
            ],
        ),
    ]
