# Generated by Django 5.2.8 on 2026-10-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0005_elector_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacionpadron',
            name='cantidad_existentes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
