# Generated by Django 5.2.8 on 2026-10-07 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0024_alcance_sin_departamento'),
        ('padron', '0007_integrar_padrones_con_develop'),
        ('parametros', '0004_claustro_organizacion_departamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSedesClaustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('eleccion_claustro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_sedes_padron', to='elecciones.eleccionclaustro')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaSedeClaustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('departamento', 'Departamento'), ('departamento_principal', 'Departamento principal'), ('nivel', 'Nivel'), ('sede_donde_cursa', 'Sede donde cursa'), ('discapacidad', 'Tiene discapacidad')], max_length=32)),
                ('operador', models.CharField(choices=[('igual', 'Es igual a'), ('en', 'Está incluido en'), ('mayor', 'Es mayor que'), ('mayor_igual', 'Es mayor o igual que'), ('menor', 'Es menor que'), ('menor_igual', 'Es menor o igual que')], max_length=16)),
                ('valor', models.CharField(help_text="Para 'Está incluido en', separe los valores con comas.", max_length=500)),
                ('orden', models.PositiveSmallIntegerField()),
                ('aplicar_a_todos', models.BooleanField(default=True)),
                ('alcances_especificos', models.ManyToManyField(blank=True, related_name='reglas_sede_claustro', to='elecciones.eleccionclaustrodepartamento')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='padron.configuracionsedesclaustro')),
                ('sede_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reglas_sede_claustro', to='parametros.sede')),
            ],
            options={
                'ordering': ('orden', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AsignacionSedePadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Sede asignada'), ('pendiente', 'Requiere una regla')], max_length=12)),
                ('calculada_en', models.DateTimeField(auto_now=True)),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion_sede_padron', to='padron.registropadron')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_sede_padron', to='parametros.sede')),
                ('regla_aplicada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_generadas', to='padron.reglasedeclaustro')),
            ],
            options={
                'ordering': ('registro_padron__eleccion_claustro_departamento__departamento__nombre', 'registro_padron__elector__apellido', 'registro_padron__elector__nombre'),
            },
        ),
        migrations.AddConstraint(
            model_name='reglasedeclaustro',
            constraint=models.UniqueConstraint(fields=('configuracion', 'orden'), name='orden_unico_regla_sede_claustro'),
        ),
    ]
