# Generated by Django 5.2.8 on 2026-10-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0008_configuracionsedesclaustro_reglasedeclaustro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacionpadron',
            name='estado',
            field=models.CharField(choices=[('previsualizada', 'Previsualizada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('padron_eliminado', 'Padrón eliminado')], default='previsualizada', max_length=16),
        ),
    ]
