# Generated by Django 5.2.16 on 2026-08-03 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0004_modelo_electoral_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('elector', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_usuario', to='elecciones.elector')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_electoral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador_sistema', 'Administrador del sistema'), ('administrador_junta', 'Administrador de junta'), ('administrativo_junta', 'Administrativo de junta'), ('autoridad_mesa', 'Autoridad de mesa'), ('elector', 'Elector')], max_length=32)),
                ('activo', models.BooleanField(default=True)),
                ('eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rol', to='elecciones.eleccion')),
                ('mesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rol', to='elecciones.mesa')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rol', to='elecciones.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rol', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'rol', 'eleccion', 'sede', 'mesa'), name='rol_unico_por_alcance')],
            },
        ),
    ]
