# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0001_initial'),
        ('padron', '0001_initial'),
        ('parametros', '0001_initial'),
        ('usuarios', '0001_perfiles_y_roles'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.AlterField(
            model_name='asignacionrol',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rol', to='mesas.mesa'),
        ),
        migrations.AlterField(
            model_name='asignacionrol',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rol', to='parametros.sede'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='elector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfil_usuario', to='padron.elector'),
        ),
        ],
    )]
