# Generated by Django 5.2.16 on 2026-09-08 03:25

import django.db.models.deletion
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0020_delete_elector_delete_envionotificacion_and_more'),
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=32)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='ParticipacionPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lista', models.CharField(max_length=20)),
                ('nombre_lista', models.CharField(blank=True, max_length=180)),
                ('activa', models.BooleanField(default=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos_participantes', to='elecciones.eleccion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='partidos.partido')),
            ],
            options={
                'ordering': ('numero_lista', 'partido__nombre'),
            },
        ),
        migrations.CreateModel(
            name='ListaCandidatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('activa', models.BooleanField(default=True)),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas_candidatos', to='elecciones.eleccionclaustro')),
                ('eleccion_claustro_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_candidatos', to='elecciones.eleccionclaustrodepartamento')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listas', to='partidos.participacionpartido')),
            ],
            options={
                'ordering': ('eleccion_claustro__claustro__nombre', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=180)),
                ('dni', models.CharField(blank=True, max_length=12, verbose_name='DNI')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('cargo', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('titular', 'Titular'), ('suplente', 'Suplente')], default='titular', max_length=12)),
                ('orden', models.PositiveSmallIntegerField(validators=(django.core.validators.MinValueValidator(1),))),
                ('activo', models.BooleanField(default=True)),
                ('elector', models.ForeignKey(blank=True, help_text='Vinculo opcional: un candidato no necesita integrar el padron.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='padron.elector')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='partidos.listacandidatos')),
            ],
            options={
                'ordering': ('cargo', 'tipo', 'orden', 'nombre'),
                'constraints': [models.UniqueConstraint(fields=('lista', 'dni'), name='candidato_unico_por_lista'), models.UniqueConstraint(fields=('lista', 'cargo', 'tipo', 'orden'), name='orden_unico_por_lista_y_cargo')],
            },
        ),
        migrations.AddConstraint(
            model_name='listacandidatos',
            constraint=models.UniqueConstraint(condition=models.Q(('eleccion_claustro_departamento__isnull', True)), fields=('participacion', 'eleccion_claustro'), name='lista_unica_por_partido_y_claustro'),
        ),
        migrations.AddConstraint(
            model_name='listacandidatos',
            constraint=models.UniqueConstraint(condition=models.Q(('eleccion_claustro_departamento__isnull', False)), fields=('participacion', 'eleccion_claustro_departamento'), name='lista_unica_por_partido_y_departamento'),
        ),
        migrations.AddConstraint(
            model_name='participacionpartido',
            constraint=models.UniqueConstraint(fields=('eleccion', 'partido'), name='partido_unico_por_eleccion'),
        ),
        migrations.AddConstraint(
            model_name='participacionpartido',
            constraint=models.UniqueConstraint(fields=('eleccion', 'numero_lista'), name='numero_lista_unico_por_eleccion'),
        ),
    ]
