# Generated by Django 5.2.16 on 2026-09-19 22:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0020_delete_elector_delete_envionotificacion_and_more'),
        ('padron', '0002_emision_qr'),
        ('partidos', '0002_catalogo_agrupaciones_y_cargos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionCandidaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('previsualizada', 'Previsualizada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='previsualizada', max_length=20)),
                ('filas', models.JSONField(default=list)),
                ('errores', models.JSONField(default=list)),
                ('advertencias', models.JSONField(default=list)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('cantidad_valida', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
        migrations.CreateModel(
            name='PuestoEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_titulares', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_suplentes', models.PositiveSmallIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('eleccion_claustro__claustro__nombre', 'eleccion_claustro_departamento__departamento__nombre', 'puesto__organo__nombre', 'puesto__nombre'),
            },
        ),
        migrations.AlterModelOptions(
            name='participacionpartido',
            options={'ordering': ('eleccion_claustro__claustro__nombre', 'numero_lista', 'nombre_lista')},
        ),
        migrations.RemoveConstraint(
            model_name='candidato',
            name='candidato_unico_por_lista',
        ),
        migrations.RemoveConstraint(
            model_name='candidato',
            name='orden_unico_por_lista_y_cargo',
        ),
        migrations.RemoveConstraint(
            model_name='participacionpartido',
            name='partido_unico_por_eleccion',
        ),
        migrations.RemoveConstraint(
            model_name='participacionpartido',
            name='numero_lista_unico_por_eleccion',
        ),
        migrations.RemoveConstraint(
            model_name='listacandidatos',
            name='lista_unica_por_partido_y_claustro',
        ),
        migrations.RemoveConstraint(
            model_name='listacandidatos',
            name='lista_unica_por_partido_y_departamento',
        ),
        migrations.AddField(
            model_name='candidato',
            name='identificador_persona',
            field=models.CharField(blank=True, help_text='Identificador consignado por la Junta; no se presume que sea DNI o legajo.', max_length=40),
        ),
        migrations.AddField(
            model_name='cargoelectivo',
            name='permite_departamento',
            field=models.BooleanField(default=False, help_text='Indica si el puesto puede configurarse para un departamento concreto.'),
        ),
        migrations.AddField(
            model_name='participacionpartido',
            name='apoderado_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='participacionpartido',
            name='apoderado_nombre',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='participacionpartido',
            name='codigo_presentacion',
            field=models.CharField(blank=True, help_text='Código interno de agrupación de filas del CSV; las presentaciones históricas pueden no tenerlo.', max_length=80),
        ),
        migrations.AddField(
            model_name='participacionpartido',
            name='eleccion_claustro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentaciones_listas', to='elecciones.eleccionclaustro'),
        ),
        migrations.AlterField(
            model_name='participacionpartido',
            name='partido',
            field=models.ForeignKey(blank=True, help_text='Referencia histórica opcional; la presentación electoral no depende de una agrupación permanente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participaciones', to='partidos.partido'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(condition=models.Q(('dni', ''), _negated=True), fields=('lista', 'dni'), name='dni_candidato_unico_por_lista'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador_persona', ''), _negated=True), fields=('lista', 'identificador_persona'), name='identificador_unico_por_lista'),
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('lista', 'tipo', 'orden'), name='orden_unico_por_lista_y_tipo'),
        ),
        migrations.AddConstraint(
            model_name='participacionpartido',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo_presentacion', ''), _negated=True), fields=('eleccion', 'codigo_presentacion'), name='presentacion_unica_por_eleccion'),
        ),
        migrations.AddField(
            model_name='importacioncandidaturas',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_candidaturas', to='elecciones.eleccion'),
        ),
        migrations.AddField(
            model_name='importacioncandidaturas',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puestoeleccion',
            name='eleccion_claustro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='puestos_electivos', to='elecciones.eleccionclaustro'),
        ),
        migrations.AddField(
            model_name='puestoeleccion',
            name='eleccion_claustro_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puestos_electivos', to='elecciones.eleccionclaustrodepartamento'),
        ),
        migrations.AddField(
            model_name='puestoeleccion',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_eleccion', to='partidos.cargoelectivo'),
        ),
        migrations.AddField(
            model_name='listacandidatos',
            name='puesto_eleccion',
            field=models.ForeignKey(blank=True, help_text='Las listas históricas pueden no tener un puesto estructurado asociado.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listas_candidatos', to='partidos.puestoeleccion'),
        ),
        migrations.AddConstraint(
            model_name='listacandidatos',
            constraint=models.UniqueConstraint(condition=models.Q(('puesto_eleccion__isnull', False)), fields=('participacion', 'puesto_eleccion'), name='lista_unica_por_presentacion_y_puesto'),
        ),
        migrations.AddConstraint(
            model_name='puestoeleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('eleccion_claustro_departamento__isnull', True)), fields=('eleccion_claustro', 'puesto'), name='puesto_unico_por_claustro'),
        ),
        migrations.AddConstraint(
            model_name='puestoeleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('eleccion_claustro_departamento__isnull', False)), fields=('eleccion_claustro_departamento', 'puesto'), name='puesto_unico_por_departamento'),
        ),
    ]
