from django.urls import path
from .views import (
    confirmar_importacion_padron,
    descargar_errores_importacion,
    descargar_plantilla_padron,
    detalle_importacion_padron,
    historial_importaciones_padron,
    previsualizar_padron,
    cambiar_estado_parametro,
    configurar_eleccion,
    cambiar_estado_eleccion,
    crear_eleccion,
    editar_alcance_sedes,
    editar_eleccion,
    editar_parametro,
    gestionar_elecciones,
    gestionar_alcances,
    gestionar_mesas,
    gestionar_parametros,
    preparar_claustro,
    preparar_eleccion,
    historial_elecciones,
    listar_elecciones,
    listar_parametros,
)

urlpatterns = [
    path("", listar_elecciones, name="lista-elecciones"),
    path("gestion/elecciones/", gestionar_elecciones, name="gestionar-elecciones"),
    path("gestion/elecciones/historial/", historial_elecciones, name="historial-elecciones"),
    path("gestion/elecciones/nueva/", crear_eleccion, name="crear-eleccion"),
    path("gestion/elecciones/<int:eleccion_id>/preparar/", preparar_eleccion, name="preparar-eleccion"),
    path("gestion/elecciones/<int:eleccion_id>/preparar/<int:claustro_id>/", preparar_claustro, name="preparar-claustro"),
    path("gestion/elecciones/<int:eleccion_id>/preparar/<int:claustro_id>/plantilla/", descargar_plantilla_padron, name="descargar-plantilla-padron"),
    path("gestion/elecciones/<int:eleccion_id>/preparar/<int:claustro_id>/padron/", previsualizar_padron, name="previsualizar-padron"),
    path("gestion/elecciones/<int:eleccion_id>/padrones/", historial_importaciones_padron, name="historial-importaciones-padron"),
    path("gestion/elecciones/<int:eleccion_id>/padrones/<int:importacion_id>/", detalle_importacion_padron, name="detalle-importacion-padron"),
    path("gestion/elecciones/<int:eleccion_id>/padrones/<int:importacion_id>/confirmar/", confirmar_importacion_padron, name="confirmar-importacion-padron"),
    path("gestion/elecciones/<int:eleccion_id>/padrones/<int:importacion_id>/errores/", descargar_errores_importacion, name="descargar-errores-importacion"),
    path("gestion/elecciones/<int:eleccion_id>/editar/", editar_eleccion, name="editar-eleccion"),
    path("gestion/elecciones/<int:eleccion_id>/configuracion/", configurar_eleccion, name="configurar-eleccion"),
    path("gestion/elecciones/<int:eleccion_id>/estado/", cambiar_estado_eleccion, name="cambiar-estado-eleccion"),
    path("gestion/elecciones/<int:eleccion_id>/alcances/", gestionar_alcances, name="gestionar-alcances"),
    path("gestion/elecciones/<int:eleccion_id>/alcances/<str:tipo>/<int:objeto_id>/", editar_alcance_sedes, name="editar-alcance-sedes"),
    path("gestion/elecciones/<int:eleccion_id>/mesas/", gestionar_mesas, name="gestionar-mesas"),
    path("gestion/parametros/", gestionar_parametros, name="gestionar-parametros"),
    path("gestion/parametros/<str:tipo>/", listar_parametros, name="listar-parametros"),
    path("gestion/parametros/<str:tipo>/nuevo/", editar_parametro, name="crear-parametro"),
    path("gestion/parametros/<str:tipo>/<int:objeto_id>/editar/", editar_parametro, name="editar-parametro"),
    path("gestion/parametros/<str:tipo>/<int:objeto_id>/estado/", cambiar_estado_parametro, name="cambiar-estado-parametro"),
]
