# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='CandidaturaAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'elecciones_candidaturaautoridad',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'elecciones_preferenciaautoridad',
            },
        ),
        migrations.CreateModel(
            name='AsignacionAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=16)),
                ('asignada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoridades_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'elecciones_asignacionautoridad',
            },
        ),
        ],
    )]
