# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoridades', '0001_initial'),
        ('mesas', '0001_initial'),
        ('padron', '0001_initial'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.AddField(
            model_name='asignacionautoridad',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoridades', to='mesas.mesa'),
        ),
        migrations.AddField(
            model_name='asignacionautoridad',
            name='registro_padron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_autoridad', to='padron.registropadron'),
        ),
        migrations.AddField(
            model_name='candidaturaautoridad',
            name='cargada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas_autoridad_cargadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidaturaautoridad',
            name='registro_padron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidatura_autoridad', to='padron.registropadron'),
        ),
        migrations.AddField(
            model_name='asignacionautoridad',
            name='candidatura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='autoridades.candidaturaautoridad'),
        ),
        migrations.AddField(
            model_name='preferenciaautoridad',
            name='registro_padron',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preferencia_autoridad', to='padron.registropadron'),
        ),
        migrations.AddField(
            model_name='preferenciaautoridad',
            name='sede_preferida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferencias_autoridad', to='parametros.sede'),
        ),
        migrations.AddField(
            model_name='preferenciaautoridad',
            name='turno_preferido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferencias_autoridad', to='parametros.turno'),
        ),
        ],
    )]
