# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elecciones', '0019_remove_asignacionmesa_mesa_and_more'),
        ('parametros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('asunto', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('roles_destinatarios', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('claustros', models.ManyToManyField(blank=True, db_table='elecciones_plantillanotificacion_claustros', related_name='plantillas_notificacion', to='parametros.claustro')),
            ],
            options={
                'db_table': 'elecciones_plantillanotificacion',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='EnvioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_notificacion', to='elecciones.eleccion')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='notificaciones.plantillanotificacion')),
            ],
            options={
                'db_table': 'elecciones_envionotificacion',
                'ordering': ('-creada_en',),
            },
        ),
        ],
    )]
