# Generated by Django 6.0.7 on 2026-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('starts_at', models.DateTimeField(verbose_name='inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='habilitada')),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='Votante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='legajo')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('dni', models.CharField(max_length=12, unique=True, verbose_name='DNI')),
            ],
            options={
                'verbose_name': 'elector',
                'verbose_name_plural': 'electores',
                'ordering': ['legajo'],
            },
        ),
    ]
