# Generated by Django 6.0.7 on 2026-07-29 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.eleccion')),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['eleccion_id', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='votante',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votantes', to='elecciones.mesa', verbose_name='mesa'),
        ),
        migrations.AddConstraint(
            model_name='mesa',
            constraint=models.UniqueConstraint(fields=('eleccion', 'numero'), name='unique_mesa_per_eleccion'),
        ),
    ]
