# Generated by Django 5.2.16 on 2026-08-03 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0003_nomenclatura_en_espanol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('hora_inicio', 'nombre'),
            },
        ),
        migrations.AlterModelOptions(
            name='elector',
            options={'ordering': ['legajo']},
        ),
        migrations.AlterModelOptions(
            name='mesa',
            options={'ordering': ['eleccion_id', 'numero']},
        ),
        migrations.AlterField(
            model_name='elector',
            name='mesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='electores', to='elecciones.mesa'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='numero'),
        ),
        migrations.CreateModel(
            name='EleccionClaustro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro', to='elecciones.claustro')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro', to='elecciones.eleccion')),
            ],
        ),
        migrations.CreateModel(
            name='EleccionClaustroDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro_departamento', to='elecciones.departamento')),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='elecciones.eleccionclaustro')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='eleccion_claustro_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.eleccionclaustrodepartamento'),
        ),
        migrations.CreateModel(
            name='RegistroPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.eleccion')),
                ('eleccion_claustro_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.eleccionclaustrodepartamento')),
                ('elector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.elector')),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionMesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_padron', to='elecciones.mesa')),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_mesa', to='elecciones.registropadron')),
            ],
        ),
        migrations.CreateModel(
            name='EleccionSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_sede', to='elecciones.eleccion')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_sede', to='elecciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='EleccionClaustroSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes_habilitadas', to='elecciones.eleccionclaustro')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro_sede', to='elecciones.sede')),
            ],
        ),
        migrations.CreateModel(
            name='EleccionClaustroDepartamentoSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion_claustro_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sedes_habilitadas', to='elecciones.eleccionclaustrodepartamento')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_departamento_sede', to='elecciones.sede')),
            ],
        ),
        migrations.AddField(
            model_name='mesa',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.sede'),
        ),
        migrations.AddField(
            model_name='mesa',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mesas', to='elecciones.turno'),
        ),
        migrations.AddConstraint(
            model_name='eleccionclaustro',
            constraint=models.UniqueConstraint(fields=('eleccion', 'claustro'), name='claustro_unico_por_eleccion'),
        ),
        migrations.AddConstraint(
            model_name='eleccionclaustrodepartamento',
            constraint=models.UniqueConstraint(fields=('eleccion_claustro', 'departamento'), name='departamento_unico_por_claustro'),
        ),
        migrations.AddConstraint(
            model_name='registropadron',
            constraint=models.UniqueConstraint(fields=('elector', 'eleccion'), name='elector_unico_por_eleccion'),
        ),
        migrations.AddConstraint(
            model_name='eleccionsede',
            constraint=models.UniqueConstraint(fields=('eleccion', 'sede'), name='sede_unica_por_eleccion'),
        ),
        migrations.AddConstraint(
            model_name='eleccionclaustrosede',
            constraint=models.UniqueConstraint(fields=('eleccion_claustro', 'sede'), name='sede_unica_por_claustro'),
        ),
        migrations.AddConstraint(
            model_name='eleccionclaustrodepartamentosede',
            constraint=models.UniqueConstraint(fields=('eleccion_claustro_departamento', 'sede'), name='sede_unica_por_departamento'),
        ),
    ]
