# Generated by Django 5.2.16 on 2026-08-03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elecciones", "0005_identificador_qr_padron")]

    operations = [
        migrations.AddField(
            model_name="eleccion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("preparada", "Preparada"),
                    ("abierta", "Abierta"),
                    ("cerrada", "Cerrada"),
                ],
                default="borrador",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="EleccionTurno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("eleccion", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="elecciones_turno", to="elecciones.eleccion")),
                ("turno", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="elecciones_turno", to="elecciones.turno")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("eleccion", "turno"), name="turno_unico_por_eleccion")],
            },
        ),
    ]
