# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elecciones", "0006_gestion_elecciones")]

    operations = [
        migrations.AddField(model_name="eleccion", name="fecha_apertura_padron_provisorio", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccion", name="fecha_cierre_padron_provisorio", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccion", name="fecha_cierre_candidaturas", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccion", name="fecha_publicacion_padron_definitivo", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccion", name="fecha_limite_justificacion_autoridades", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccion", name="fecha_limite_justificacion_electores", field=models.DateField(blank=True, null=True)),
    ]
