# Generated by Django 6.0.7 on 2026-08-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0007_fechas_administrativas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechaAdministrativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('roles_destinatarios', models.JSONField(default=list)),
                ('asunto_notificacion', models.CharField(max_length=180)),
                ('mensaje_notificacion', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('claustros', models.ManyToManyField(related_name='fechas_administrativas', to='elecciones.claustro')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='FechaAdministrativaEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fechas_administrativas', to='elecciones.eleccion')),
                ('fecha_administrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='elecciones.fechaadministrativa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('eleccion', 'fecha_administrativa'), name='fecha_administrativa_unica_por_eleccion')],
            },
        ),
    ]
