# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elecciones", "0008_fechaadministrativa_fechaadministrativaeleccion")]

    operations = [
        migrations.RemoveField(model_name="sede", name="codigo"),
        migrations.RemoveField(model_name="claustro", name="codigo"),
    ]
