# Generated by Django 5.2.16 on 2026-08-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elecciones", "0009_quitar_codigos_sede_y_claustro")]

    operations = [
        migrations.AddField(model_name="eleccionclaustro", name="fecha_votacion", field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name="eleccionclaustro", name="maximo_votantes_por_mesa", field=models.PositiveIntegerField(blank=True, null=True)),
    ]
