# Generated by Django 6.0.7 on 2026-08-03 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0010_preparacion_por_claustro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electronico'),
        ),
        migrations.CreateModel(
            name='ImportacionPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='padrones/%Y/%m/%d')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('huella_archivo', models.CharField(max_length=64)),
                ('estado', models.CharField(choices=[('previsualizada', 'Previsualizada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='previsualizada', max_length=16)),
                ('cantidad_filas', models.PositiveIntegerField(default=0)),
                ('cantidad_validas', models.PositiveIntegerField(default=0)),
                ('cantidad_errores', models.PositiveIntegerField(default=0)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to='elecciones.eleccion')),
                ('eleccion_claustro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to='elecciones.eleccionclaustro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importaciones_padron', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
        migrations.CreateModel(
            name='ErrorImportacionPadron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.PositiveIntegerField(blank=True, null=True)),
                ('campo', models.CharField(blank=True, max_length=64)),
                ('mensaje', models.CharField(max_length=300)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='elecciones.importacionpadron')),
            ],
            options={
                'ordering': ('fila', 'id'),
            },
        ),
    ]
