# Generated by Django 6.0.7 on 2026-08-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0011_elector_correo_electronico_importacionpadron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='generada_automaticamente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registropadron',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_padron', to='elecciones.sede'),
        ),
    ]
