# Generated by Django 6.0.7 on 2026-08-03 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0012_mesa_generada_automaticamente_registropadron_sede'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=16)),
                ('asignada_en', models.DateTimeField(auto_now_add=True)),
                ('respondida_en', models.DateTimeField(blank=True, null=True)),
                ('asignada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoridades_asignadas', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autoridades', to='elecciones.mesa')),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_autoridad', to='elecciones.registropadron')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenciaAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='preferencia_autoridad', to='elecciones.registropadron')),
                ('sede_preferida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferencias_autoridad', to='elecciones.sede')),
                ('turno_preferido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferencias_autoridad', to='elecciones.turno')),
            ],
        ),
    ]
