# Generated by Django 6.0.7 on 2026-08-03 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0013_asignacionautoridad_preferenciaautoridad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='maximo_autoridades_por_mesa',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.CreateModel(
            name='CandidaturaAutoridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargada_en', models.DateTimeField(auto_now_add=True)),
                ('cargada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas_autoridad_cargadas', to=settings.AUTH_USER_MODEL)),
                ('registro_padron', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidatura_autoridad', to='elecciones.registropadron')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionautoridad',
            name='candidatura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='elecciones.candidaturaautoridad'),
        ),
    ]
