# Generated by Django 6.0.7 on 2026-08-04 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0015_tipojustificativo_justificativoausencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160, unique=True)),
                ('asunto', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('roles_destinatarios', models.JSONField(default=list)),
                ('activa', models.BooleanField(default=True)),
                ('claustros', models.ManyToManyField(blank=True, related_name='plantillas_notificacion', to='elecciones.claustro')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='EnvioNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=180)),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=16)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('enviada_en', models.DateTimeField(blank=True, null=True)),
                ('leida_en', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('eleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_notificacion', to='elecciones.eleccion')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios', to='elecciones.plantillanotificacion')),
            ],
            options={
                'ordering': ('-creada_en',),
            },
        ),
    ]
