# Generated by Django 5.2.8 on 2026-08-09 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0016_plantillanotificacion_envionotificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elector',
            name='mesa',
        ),
    ]
