# Generated by Django 5.2.8 on 2026-08-09 23:20

import secrets
import string

from django.db import migrations, models


ALFABETO_CODIGO_QR = string.ascii_uppercase + string.digits


def generar_codigo_qr():
    return "".join(secrets.choice(ALFABETO_CODIGO_QR) for _ in range(8))


def backfill_identificador_qr_corto(apps, schema_editor):
    RegistroPadron = apps.get_model("elecciones", "RegistroPadron")
    db_alias = schema_editor.connection.alias
    usados = set()

    for registro in RegistroPadron.objects.using(db_alias).order_by("pk"):
        while True:
            candidato = generar_codigo_qr()
            if candidato not in usados and not RegistroPadron.objects.using(db_alias).filter(identificador_qr=candidato).exclude(pk=registro.pk).exists():
                usados.add(candidato)
                break
        RegistroPadron.objects.using(db_alias).filter(pk=registro.pk).update(identificador_qr=candidato)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('elecciones', '0017_remove_elector_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropadron',
            name='identificador_qr',
            field=models.CharField(blank=True, editable=False, max_length=36, unique=True),
        ),
        migrations.RunPython(backfill_identificador_qr_corto, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='registropadron',
            name='identificador_qr',
            field=models.CharField(blank=True, editable=False, max_length=8, unique=True),
        ),
    ]
