# Generated by Django 5.2.16 on 2026-09-07 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0018_alter_registropadron_identificador_qr'),
        ('parametros', '0001_initial'),
    ]

    operations = [migrations.SeparateDatabaseAndState(
        database_operations=[],
        state_operations=[
        migrations.RemoveField(
            model_name='asignacionmesa',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='asignacionmesa',
            name='registro_padron',
        ),
        migrations.RemoveField(
            model_name='candidaturaautoridad',
            name='cargada_por',
        ),
        migrations.RemoveField(
            model_name='candidaturaautoridad',
            name='registro_padron',
        ),
        migrations.RemoveField(
            model_name='plantillanotificacion',
            name='claustros',
        ),
        migrations.AlterField(
            model_name='eleccionclaustro',
            name='claustro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro', to='parametros.claustro'),
        ),
        migrations.RemoveField(
            model_name='fechaadministrativa',
            name='claustros',
        ),
        migrations.AlterField(
            model_name='eleccionclaustrodepartamento',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro_departamento', to='parametros.departamento'),
        ),
        migrations.RemoveField(
            model_name='registropadron',
            name='elector',
        ),
        migrations.RemoveField(
            model_name='envionotificacion',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='envionotificacion',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='envionotificacion',
            name='plantilla',
        ),
        migrations.RemoveField(
            model_name='errorimportacionpadron',
            name='importacion',
        ),
        migrations.AlterField(
            model_name='fechaadministrativaeleccion',
            name='fecha_administrativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='parametros.fechaadministrativa'),
        ),
        migrations.RemoveField(
            model_name='importacionpadron',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='importacionpadron',
            name='eleccion_claustro',
        ),
        migrations.RemoveField(
            model_name='importacionpadron',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='justificativoausencia',
            name='registro_padron',
        ),
        migrations.RemoveField(
            model_name='justificativoausencia',
            name='resuelta_por',
        ),
        migrations.RemoveField(
            model_name='justificativoausencia',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='eleccion_claustro_departamento',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='sede',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='turno',
        ),
        migrations.RemoveField(
            model_name='preferenciaautoridad',
            name='registro_padron',
        ),
        migrations.RemoveField(
            model_name='preferenciaautoridad',
            name='sede_preferida',
        ),
        migrations.RemoveField(
            model_name='preferenciaautoridad',
            name='turno_preferido',
        ),
        migrations.RemoveField(
            model_name='registropadron',
            name='eleccion',
        ),
        migrations.RemoveField(
            model_name='registropadron',
            name='eleccion_claustro_departamento',
        ),
        migrations.RemoveField(
            model_name='registropadron',
            name='sede',
        ),
        migrations.AlterField(
            model_name='eleccionsede',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_sede', to='parametros.sede'),
        ),
        migrations.AlterField(
            model_name='eleccionclaustrosede',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_claustro_sede', to='parametros.sede'),
        ),
        migrations.AlterField(
            model_name='eleccionclaustrodepartamentosede',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_departamento_sede', to='parametros.sede'),
        ),
        migrations.AlterField(
            model_name='eleccionturno',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='elecciones_turno', to='parametros.turno'),
        ),
        migrations.DeleteModel(
            name='AsignacionAutoridad',
        ),
        migrations.DeleteModel(
            name='AsignacionMesa',
        ),
        migrations.DeleteModel(
            name='CandidaturaAutoridad',
        ),
        migrations.DeleteModel(
            name='Claustro',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        ],
    )]
