# Generated by Django 5.2.16 on 2026-09-07 03:03

from django.db import migrations


MODELOS_MOVIDOS = {
    "asignacionautoridad": "autoridades",
    "asignacionmesa": "mesas",
    "candidaturaautoridad": "autoridades",
    "claustro": "parametros",
    "departamento": "parametros",
    "elector": "padron",
    "envionotificacion": "notificaciones",
    "errorimportacionpadron": "padron",
    "fechaadministrativa": "parametros",
    "importacionpadron": "padron",
    "justificativoausencia": "justificativos",
    "mesa": "mesas",
    "plantillanotificacion": "notificaciones",
    "preferenciaautoridad": "autoridades",
    "registropadron": "padron",
    "sede": "parametros",
    "tipojustificativo": "justificativos",
    "turno": "parametros",
}


def actualizar_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    alias = schema_editor.connection.alias if schema_editor is not None else "default"
    content_types = ContentType.objects.using(alias)
    for modelo, app_destino in MODELOS_MOVIDOS.items():
        anterior = content_types.filter(app_label="elecciones", model=modelo).first()
        if anterior is None:
            continue
        duplicado = content_types.filter(app_label=app_destino, model=modelo).first()
        if duplicado is not None:
            raise RuntimeError(
                f"Ya existe el ContentType {app_destino}.{modelo}; "
                "resuelva el duplicado antes de continuar.",
            )
        anterior.app_label = app_destino
        anterior.save(using=alias, update_fields=("app_label",))


def revertir_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    alias = schema_editor.connection.alias if schema_editor is not None else "default"
    content_types = ContentType.objects.using(alias)
    for modelo, app_origen in MODELOS_MOVIDOS.items():
        actual = content_types.filter(app_label=app_origen, model=modelo).first()
        if actual is None:
            continue
        duplicado = content_types.filter(app_label="elecciones", model=modelo).first()
        if duplicado is not None:
            raise RuntimeError(
                f"Ya existe el ContentType elecciones.{modelo}; "
                "resuelva el duplicado antes de revertir.",
            )
        actual.app_label = "elecciones"
        actual.save(using=alias, update_fields=("app_label",))


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_alter_registroparticipacion_mesa_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('elecciones', '0019_remove_asignacionmesa_mesa_and_more'),
        ('usuarios', '0002_alter_asignacionrol_mesa_alter_asignacionrol_sede_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.DeleteModel(
            name='Elector',
        ),
        migrations.DeleteModel(
            name='EnvioNotificacion',
        ),
        migrations.DeleteModel(
            name='PlantillaNotificacion',
        ),
        migrations.DeleteModel(
            name='ErrorImportacionPadron',
        ),
        migrations.DeleteModel(
            name='FechaAdministrativa',
        ),
        migrations.DeleteModel(
            name='ImportacionPadron',
        ),
        migrations.DeleteModel(
            name='JustificativoAusencia',
        ),
        migrations.DeleteModel(
            name='TipoJustificativo',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
        migrations.DeleteModel(
            name='PreferenciaAutoridad',
        ),
        migrations.DeleteModel(
            name='RegistroPadron',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
            ],
        ),
        migrations.RunPython(actualizar_content_types, revertir_content_types),
    ]
